### ISSUE TITLE
Smart Connect not making Smart Connection work

### ISSUE THREAD

**Issue by matlemai** [brianpetro/smart-connect#15]
Hi - I recently paid for the subscription for Smart Connect but it is still not working. 

I detailed my issues here ~3 weeks ago : https://github.com/brianpetro/obsidian-smart-connections/issues/356

Obsidian is essentially unusable when Smart Connection is activated, and I can't change any of the plugin's parameters. 

Q1: How can I force pause/interrupt the process to link it to smart connect?

When I start obsidian (1.6.4) with the Smart Connection plugin installed (2.1.74) and Smart Connect (1.1.58) already active in the background ("Connected to https://connect.smartconnections.app), nothing changes. It still always stalls around the same spot.

[Smart Connections]
Making Smart Connections...
Progress: 1980 / 5514 files

... and I must remove the plugin entirely after quitting Obsidian if I want to use the app. 

Q2: Any idea what the problem may be?

If there is no fix in sight, I will just cancel my subscription.

Thanks
Mathieu

**Comment by christianngarcia** [comment]
We will be looking into this today and will get back to you soon. 🌼

**Comment by matlemai** [comment]
ok thanks

**Comment by brianpetro** [comment]
Hi @matlemai 

Apologies for letting this issue slip through the cracks!

To get this issue fixed ASAP, I will follow up by replying to your welcome email shortly.

To clarify how subscribers can receive priority help & support, I will update the welcome email so it's clearer for future subscribers.

Lastly, I went ahead and refunded your first-month payment since this issue has slipped through the cracks for so long.

Thanks for your patience!
🌴 Brian

**Comment by matlemai** [comment]
ok thanks Brian - much appreciated!
Mathieu

**Comment by brianpetro** [comment]
😊 Email sent  🌴
