### ISSUE TITLE
how can i pay to get a license key?

### ISSUE THREAD

**Issue by lizhuo8716** [brianpetro/smart-connect#6]
i cannot find a way to get the license key and use the smart connect app...

**Comment by InquisitiveBadger** [comment]
Seconded. Did you find a way?

**Comment by brianpetro** [comment]
Hi @lizhuo8716 & @InquisitiveBadger 

Soon, there will also be a monthly subscription option for connection keys. 

Currently, only supporters of the [Obsidian plugin ](https://github.com/brianpetro/obsidian-smart-connections) can get connection keys because Smart Connect works best when used with Obsidian vaults. However, Smart Connect will soon be able to make [Smart Environments](https://www.youtube.com/watch?v=0obRntW8Cto) for code repositories and other markdown note platforms. 

🌴

**Comment by InquisitiveBadger** [comment]
> Hi @lizhuo8716 & @InquisitiveBadger
> 
> Soon, there will also be a monthly subscription option for connection keys.
> 
> Currently, only supporters of the [Obsidian plugin ](https://github.com/brianpetro/obsidian-smart-connections) can get connection keys because Smart Connect works best when used with Obsidian vaults. However, Smart Connect will soon be able to make [Smart Environments](https://www.youtube.com/watch?v=0obRntW8Cto) for code repositories and other markdown note platforms.
> 
> 🌴

A little confused by this. I'm currently using the plugin in Obsidian via my OpenAI API key for Smart Chat (haven't tried Views & Embedding yet, though the keys are in there). I also have ChatGPT Plus and can access Smart Connect — Obsidian. 

Does Smart Connect have any features for Obsidian in particular beyond the above? Editing prompts and 'Find Actions' is greyed out, so I'm assuming that's two of them?

Thanks for all your hard work on this!

**Comment by brianpetro** [comment]
@InquisitiveBadger there will be more details soon 🌴
